create table if not exists public.text_ads (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists text_ads_slug_idx
on public.text_ads(slug);

create index if not exists text_ads_created_at_idx
on public.text_ads(created_at desc);

alter table public.text_ads enable row level security;

-- Сервер использует service_role key,
-- поэтому публичная INSERT policy не нужна.